{"name": "test_tablename", "status": "failed", "statusDetails": {"message": "AssertionError: Regex didn't match: 'random_table' not found in 'entered_table'", "trace": "self = <DatabaseLoggerSQL.unit_tests.test_01.DatabaseTest testMethod=test_tablename>\n\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_tablename(self):\n        tablename:str = 'entered_table'\n        event_01 = EventLogger(tablename)\n    \n>       self.assertRegex(event_01.TABLE_NAME, 'random_table')\nE       AssertionError: Regex didn't match: 'random_table' not found in 'entered_table'\n\nunit_tests/test_01.py:76: AssertionError"}, "attachments": [{"name": "stdout", "source": "8bb093a4-7907-4eab-9bcb-4a4ee4c55d12-attachment.txt", "type": "text/plain"}], "start": 1641211078908, "stop": 1641211079465, "uuid": "11d1c16d-16c2-4b5f-a96e-077863157121", "historyId": "4f7fb55133c1e4c48d8b2ffc5a081e9d", "testCaseId": "942d3fa10cb4be588f676ed2016e7690", "fullName": "unit_tests.test_01.DatabaseTest#test_tablename", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "unit_tests"}, {"name": "suite", "value": "test_01"}, {"name": "subSuite", "value": "DatabaseTest"}, {"name": "host", "value": "prithoo-techvariable"}, {"name": "thread", "value": "41642-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "unit_tests.test_01"}]}