{"name": "test_tablename", "status": "failed", "statusDetails": {"message": "AssertionError: Regex didn't match: 'random_table' not found in 'entered_table'", "trace": "self = <DatabaseLoggerSQL.unit_tests.test_01.DatabaseTest testMethod=test_tablename>\n\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_tablename(self):\n        tablename:str = 'entered_table'\n        event_01 = EventLogger(tablename)\n    \n>       self.assertRegex(event_01.TABLE_NAME, 'random_table')\nE       AssertionError: Regex didn't match: 'random_table' not found in 'entered_table'\n\nunit_tests/test_01.py:76: AssertionError"}, "attachments": [{"name": "stdout", "source": "8e7c777e-d1a7-486c-9b1e-684f07c268a9-attachment.txt", "type": "text/plain"}], "start": 1641211106921, "stop": 1641211107475, "uuid": "0fa95f68-732a-4a6d-9203-e69bf7db6d39", "historyId": "4f7fb55133c1e4c48d8b2ffc5a081e9d", "testCaseId": "942d3fa10cb4be588f676ed2016e7690", "fullName": "unit_tests.test_01.DatabaseTest#test_tablename", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "unit_tests"}, {"name": "suite", "value": "test_01"}, {"name": "subSuite", "value": "DatabaseTest"}, {"name": "host", "value": "prithoo-techvariable"}, {"name": "thread", "value": "41895-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "unit_tests.test_01"}]}